version: "3.3"
services:
  # aimelia-data:
  #   build:
  #     context: .
  #     dockerfile: ./multinode/data/Dockerfile
  #   working_dir: /dataNode
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - ./multinode/data:/nodeNode/
  #   networks:
  #     - default

  aimelia-data:
    build:
      context: .
      dockerfile: ./src/nodes/data/Dockerfile
    working_dir: /src
    ports:
      - 8000:8000
    volumes:
      - ./src:/src
    networks:
      - default

  aimelia-inference:
    build:
      context: .
      dockerfile: ./src/nodes/inference/Dockerfile
    working_dir: /src
    ports:
      - 8001:8001
    volumes:
      - ./src:/src
    networks:
      - default
