version: "3.3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /aimelia
    ports:
      - 8000:8000
    volumes:
      - ./aimelia:/aimelia
    networks:
      - default
