version: "3.3"
services:
  aimelia:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /src
    ports:
      - 8000:8000
    volumes:
      - ./src:/src
    networks:
      - default
