version: "3.3"
services:
  aimelia-data:
    build:
      context: .
      dockerfile: ./multinode/data/Dockerfile
    working_dir: /dataNode
    ports:
      - 8000:8000
    volumes:
      - ./multinode/data:/nodeNode/
    networks:
      - default

  aimelia-inference:
    build:
      context: .
      dockerfile: ./multinode/inference/Dockerfile
    working_dir: /inferenceNode
    ports:
      - 8001:8001
    volumes:
      - ./multinode/inference:/inferenceNode/
    networks:
      - default
